name: Auto approve and merge PRs by dependabot

on:
  pull_request:
  check_run:
    types: [ completed ]

permissions:
  pull-requests: write

jobs:
  autoapprove:
    name: Auto Approve and automerge PR by dependabot
    runs-on: ubuntu-latest
    steps:
      - name: Auto approve
        uses: hmarr/auto-approve-action@v3.2.1
        # Perform the auto approve action only when the PR is raised by dependabot
        if: github.actor == 'theprashantyadav'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # merge only dependabot PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_FILTER_AUTHOR: 'theprashantyadav'
          MERGE_METHOD: "merge"
          MERGE_DELETE_BRANCH: "true"
          MERGE_LABELS: "dependencies,automerge"
          MERGE_REQUIRED_APPROVALS: "1"
