name: Auto approve and merge PRs by dependabot

on:
  pull_request:
    types:
      - labeled
      - synchronize

permissions:
  pull-requests: write

jobs:
  autoapprove:
    name: Auto Approve a PR by dependabot
    runs-on: ubuntu-latest
    steps:
      - name: Auto approve
        uses: hmarr/auto-approve-action@v3.2.1
        if: github.actor == 'theprashantyadav'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  automerge:
    name: Automerge Dependabot PR
    runs-on: ubuntu-latest
    needs: autoapprove
    if: success() && github.event_name == 'pull_request'
    steps:
      - name: Wait for all checks to pass
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { data: checksResponse } = await github.checks.listForRef({
            ...context.repo,
            ref: context.payload.pull_request.head.sha,
          });

          const incompleteChecks = checksResponse.check_runs.filter(check => check.conclusion === null);

          if (incompleteChecks.length > 0) {
            console.log('Not all checks have completed. Exiting.');
            process.exit(78); // Exit code 78 indicates a neutral result
          }

          const failedChecks = checksResponse.check_runs.filter(check => check.conclusion !== 'success');

          if (failedChecks.length > 0) {
            console.log('The following checks failed:');
            failedChecks.forEach(failedCheck => {
              console.log(`${failedCheck.name}: ${failedCheck.conclusion}`);
            });
            process.exit(78); // Exit code 78 indicates a neutral result
          }

      - name: Automerge
        uses: pascalgn/automerge-action@v0.15.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_FILTER_AUTHOR: 'theprashantyadav'
          MERGE_METHOD: "merge"
          MERGE_DELETE_BRANCH: "true"
          MERGE_LABELS: "dependencies,automerge"
          MERGE_REQUIRED_APPROVALS: ""
