name: Dependabot auto-approve
on:
  pull_request:
    types:
      - synchronize
      - opened
      - reopened
  check_suite:
    types:
      - completed

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.actor == 'theprashantyadav'
    steps:
      - name: Debug Outputs
          run: |
            echo "all-checks-completed: ${{ steps.get-status.outputs.all-checks-completed }}"
            echo "all-checks-passed: ${{ steps.get-status.outputs.all-checks-passed }}"
      - name: Approve a PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Enable auto-merge for Dependabot PRs
        # if: contains(steps.metadata.outputs.dependency-names, 'my-dependency') && steps.metadata.outputs.update-type == 'version-update:semver-patch'
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
