name: Auto approve and merge PRs by dependabot

on:
  pull_request:
    types:
      - synchronize
      - opened
      - reopened
  check_suite:
    types:
      - completed

jobs:
  autoapprove:
    name: Auto Approve a PR by dependabot
    runs-on: ubuntu-latest
    if: github.actor == 'theprashantyadav' && github.event_name == 'pull_request'
    steps:
      - name: Auto approve
        uses: hmarr/auto-approve-action@v3.2.1
        # Perform the auto approve action only when the PR is raised by dependabot
        if: github.actor == 'theprashantyadav'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  automerge:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    needs: autoapprove
    steps:
      - id: automerge
        name: automerge
        uses: pascalgn/automerge-action@v0.15.6
        if: ${{ needs.auto_merge.outputs.success == 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_FILTER_AUTHOR: 'theprashantyadav'
          MERGE_METHOD: "merge"
          MERGE_DELETE_BRANCH: "true"
          MERGE_LABELS: "dependencies,automerge"
          MERGE_REQUIRED_APPROVALS: ""


