name: Auto approve and merge PRs by dependabot

# on:
#   pull_request:
#     types:
#       - labeled
#       - unlabeled
#       - synchronize
#       - opened
#       - edited
#       - ready_for_review
#       - reopened
#       - unlocked
#   check_run:
#     types:
#       - [ completed ]

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}

jobs:
  auto-approve:
    name: Auto Approve a PR by dependabot
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
     # Perform the auto approve action only when the PR is raised by dependabot 
    if: github.actor == 'cloudlovely'
    steps:
      - name: Auto approve
        uses: hmarr/auto-approve-action@v3.2.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  auto-merge:  
    runs-on: ubuntu-latest
    steps:
      - id: automerge
        name: automerge
        uses: pascalgn/automerge-action@v0.15.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_FILTER_AUTHOR: 'cloudlovely'
          MERGE_METHOD: "merge"
          MERGE_DELETE_BRANCH: "true"
          MERGE_LABELS: "dependencies,automerge"
          MERGE_REQUIRED_APPROVALS: "0"


