name: Auto approve and merge PRs by dependabot

on:
  pull_request:

jobs:
  autoapprove:
    name: Auto Approve a PR by dependabot
    runs-on: ubuntu-latest
    steps:
      - name: Auto approve
        uses: hmarr/auto-approve-action@v3.2.1
        # Perform the auto approve action only when the PR is raised by dependabot
        if: github.actor == 'theprashantyadav'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

 auto_merge_if_checks_pass:
    needs: auto_merge
    runs-on: ubuntu-latest

    steps:
      - name: Auto Merge if checks pass
        if: ${{ needs.auto_merge.outputs.success == 'true' }}
        run: |
          # Your auto-merge logic here
          # For example, using Git commands to merge the pull request
          git checkout master
          git merge ${{ github.event.before }}

  automerge:
    runs-on: ubuntu-latest
#    needs: autoapprove
#    if: ${{ success() && github.event_name == 'check_suite' && github.event.action == 'completed' }}
    steps:
      - id: automerge
        name: automerge
        uses: pascalgn/automerge-action@v0.15.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_FILTER_AUTHOR: 'theprashantyadav'
          MERGE_METHOD: "merge"
          MERGE_DELETE_BRANCH: "true"
          MERGE_LABELS: "dependencies,automerge"
          MERGE_REQUIRED_APPROVALS: ""
