name: automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}
  check_run:
      types: [ rerequested, completed ]
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - id: automerge
        name: automerge
        uses: pascalgn/automerge-action@v0.15.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_FILTER_AUTHOR: "theprashantyadav"
          MERGE_METHOD: "merge"
          MERGE_DELETE_BRANCH: "true"
#      - name: Merge if branch can be merged automatically
#        if: steps.check-merge.outputs.mergeable == 'true'
#        run: |
#          echo "Merging the pull request."
#          git config --global user.email "github-actions@github.com"
#          git config --global user.name "GitHub Actions"
#          git checkout -b auto-merge-branch ${{ github.event.pull_request.base.sha }}
#          git merge --no-edit ${{ github.event.pull_request.head.sha }}
#          git push origin auto-merge-branch
#        shell: bash
