name: Auto approve and merge PRs by dependabot

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  check_run:
    types:
      - completed

jobs:
  autoapprove:
    name: Auto Approve a PR by dependabot
    runs-on: ubuntu-latest
    steps:
      - name: Auto approve
        uses: hmarr/auto-approve-action@v3.2.1
        # Perform the auto approve action only when the PR is raised by dependabot
        if: github.actor == 'theprashantyadav'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  automerge:
    name: Automerge PR
    runs-on: ubuntu-latest
    needs: autoapprove
    steps:
      - name: Wait for all checks to pass
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { data: checks } = await github.checks.listForRef({
            ...context.repo,
            ref: context.payload.pull_request.head.sha,
          });

          const allChecksPassed = checks.check_runs.every((check) => check.conclusion === 'success');

          if (!allChecksPassed) {
            console.log('Not all checks have passed. Exiting.');
            process.exit(78); // Exit code 78 indicates a neutral result
          }
      - name: Automerge
        uses: pascalgn/automerge-action@v0.15.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_FILTER_AUTHOR: 'theprashantyadav'
          MERGE_METHOD: "merge"
          MERGE_DELETE_BRANCH: "true"
          MERGE_LABELS: "dependencies,automerge"
          MERGE_REQUIRED_APPROVALS: ""
