name: 'Create README.md file'
on:
  push:
    branches:
      - master

jobs:
  readme-create:
    name: 'readme-create'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master

      - name: 'Set up Python 3.7'
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 'create readme'
        uses: 'clouddrove/github-actions@9.0.3'
        with:
          actions_subcommand: 'readme'
          GITHUB_TOKEN: "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"
        env:
          GITHUB_TOKEN: "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"

      - name: 'pre-commit check errors'
        uses: pre-commit/action@v3.0.0
        continue-on-error: true

      - name: 'pre-commit fix erros'
        uses: pre-commit/action@v3.0.0
        continue-on-error: true

      - name: 'push readme'
        uses: 'clouddrove/github-actions@9.0.3'
        continue-on-error: true
        with:
          actions_subcommand: 'push'
        env:
          GITHUB_TOKEN: "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"

      - name: 'Slack Notification'
        uses: clouddrove/action-slack@v2
        with:
          status: ${{ job.status }}
          fields: repo,author
          author_name: 'CloudDrove'
        env:
          GITHUB_TOKEN: "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"
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_TERRAFORM }} # required
        if: always()
