name: run checks

on:
  pull_request:
    types:
      - synchronize
      - opened
      - reopened
  workflow_run:
    workflows: ["Auto Assign PRs", "changelog", "tf-checks", "tfsec"]
    types:
      - completed
