name: Release
on:
  workflow_run:
    workflows: ["Run Tests"]
    branches: [main]
    types:
      - completed
jobs:
  deploy-packages:
    # the 2nd condition
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    (...)
