name: run checks

on:
  pull_request:
    types:
      - synchronize
      - opened
      - reopened
  workflow_run:
    workflows: ["Auto Assign PRs", "changelog", "tf-checks", "tfsec"]
    types:
      - completed

jobs:
  test_something:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/create-outputs@v0.0.0-fake
        id: test
      - uses: LouisBrunner/checks-action@v1.6.1
        if: always()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

