name: Auto approve and merge PRs by dependabot
on:
  pull_request:
    types:
      - synchronize
      - opened
      - reopened
  workflow_run:
    workflows: ["Auto Assign PRs", "changelog", "tf-checks", "tfsec", "Create README.md file"]
    types:
      - completed
jobs:
  test-packages:
    runs-on: ubuntu-latest
    steps:
      - name: tfsec commenter for PR
        uses: actions/checkout@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB}}
