name: run checks

on:
  workflow_run:
    workflows: ["Auto Assign PRs", "changelog", "tf-checks", "tfsec"]
    types:
      - completed

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

