name: run checks

on:
  pull_request:
    types:
      - synchronize
      - opened
      - reopened
  workflow_run:
    workflows: ["Auto Assign PRs", "changelog", "tf-checks", "tfsec"]
    types:
      - completed

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run a simple check
        run: echo "Checking..."

