name: Run Checks

on:
  workflow_run:
    workflows: ["Auto Assign PRs", "changelog", "tf-checks", "tfsec", "Create README.md file"]
    types:
      - completed
jobs:
  check_workflow_status:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Check Workflow Status
        run: |
          echo "The triggering workflow was successful!"
